# version: "3.8"
services:
  go-nacon:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/github.com/nacon
    environment:
      - GO111MODULE=on
      - GOPROXY=https://goproxy.io
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 3s
      retries: 10
  stressclient:
    build:
      context: .
      dockerfile: Dockerfile
      target: stressclient
    depends_on:
      - go-nacon
    environment:
      - GO111MODULE=on
      - GOPROXY=https://goproxy.io
      - SERVER_URL=http://go-nacon:8080
      - GRPC_SERVER_URL=go-nacon:8080
  cli:
    build:
      context: .
      dockerfile: Dockerfile
      target: cli
    depends_on:
      - go-nacon
    environment:
      - SERVER_URL=http://go-nacon:8080
      - GRPC_SERVER_URL=go-nacon:8080
    tty: true # Allocate a pseudo-TTY
    stdin_open: true # Keep stdin open for input
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    depends_on:
      - go-nacon
    environment:
      - GO111MODULE=on
      - GOPROXY=https://goproxy.io
