version: "3.8"
services:
  go-nacon:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/github.com/nacon
      - ./.db-data:/data
    environment:
      - GO111MODULE=on
      - GOPROXY=https://goproxy.io
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DB_PATH=${DB_PATH}
      # Rate Limiter
      - RATE_LIMIT=${RATE_LIMIT}
      - RATE_BURST=${RATE_BURST}
      # Circuit Breaker
      - CB_MAX_REQUESTS=${CB_MAX_REQUESTS}
      - CB_INTERVAL=${CB_INTERVAL}
      - CB_TIMEOUT=${CB_TIMEOUT}
      - CB_CONSECUTIVE_FAILURES=${CB_CONSECUTIVE_FAILURES}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 3s
      retries: 10
  stressclient:
    build:
      context: .
      dockerfile: Dockerfile
      target: stressclient
    depends_on:
      - go-nacon
    environment:
      - GO111MODULE=on
      - GOPROXY=https://goproxy.io
      - SERVER_URL=http://go-nacon:8080
      - GRPC_SERVER_URL=go-nacon:8080
      # Stress test configuration
      - STRESS_DURATION=${STRESS_DURATION:-60s}
      - GRPC_CONCURRENCY=${GRPC_CONCURRENCY:-10}
      - HTTP_CONCURRENCY=${HTTP_CONCURRENCY:-2}
      - REQUEST_DELAY=${REQUEST_DELAY:-5ms}
      # Admin credentials
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin-key-456}
      # Delete operation configuration
      - DELETE_TIMEOUT=${DELETE_TIMEOUT:-10s}
      - DELETE_RETRIES=${DELETE_RETRIES:-3}
  cli:
    build:
      context: .
      dockerfile: Dockerfile
      target: cli
    depends_on:
      - go-nacon
    volumes:
      - ./.db-data:/data
    environment:
      - SERVER_URL=${HTTP_SERVER_URL}
      - GRPC_SERVER_URL=${GRPC_SERVER_URL}
      - DB_PATH=${DB_PATH}
    tty: true
    stdin_open: true
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    depends_on:
      - go-nacon
    environment:
      - GO111MODULE=on
      - GOPROXY=https://goproxy.io
      - SERVER_URL=${HTTP_SERVER_URL}
      - GRPC_SERVER_URL=${GRPC_SERVER_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DB_PATH=${DB_PATH}
      # Rate Limiter
      - RATE_LIMIT=${RATE_LIMIT}
      - RATE_BURST=${RATE_BURST}
      # Circuit Breaker
      - CB_MAX_REQUESTS=${CB_MAX_REQUESTS}
      - CB_INTERVAL=${CB_INTERVAL}
      - CB_TIMEOUT=${CB_TIMEOUT}
      - CB_CONSECUTIVE_FAILURES=${CB_CONSECUTIVE_FAILURES}

# volumes:
#   db-data:
